name = "quote-uploader"
main = "quote-uploader.js"  # Path to your main Worker script
compatibility_date = "2024-10-07"

# Exclude quotes.json from being bundled in script by build
[build.upload]
exclude = ["quotes.json"]
